services:
  server:
    build:
      dockerfile: Dockerfile

    env_file: .env

    user: server

    volumes:
      - ./dilithium.key:/app/dilithium.key
      - ./pqcow-server.db:/app/pqcow-server.db

    stop_signal: SIGINT

    ports:
      - "8080:8080"

    restart: always

    entrypoint: [ "python", "tests/__server__.py" ]
